name: 'Octo Organization CI'
true:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run a one-line script'
        run: 'echo Hello from Octo Organization'
